FROM lsiocommunity/organizr

RUN rm -f /config/www/users.db
# RUN rm -f /config/www/Dashboard/config/config.php

COPY config/users.db /config/www/users.db
# COPY config/config.php /config/www/Dashboard/config/config.php
